# Generated by Django 3.2.5 on 2021-10-22 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
