# Generated by Django 3.2.5 on 2021-10-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0003_countries_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Countries',
            new_name='Country',
        ),
    ]
