# Generated by Django 3.2.5 on 2021-10-22 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0004_rename_countries_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('about', models.TextField(max_length=1024)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('maps_embed', models.TextField(max_length=3000, null=True)),
                ('building_number_name', models.CharField(max_length=25)),
                ('building_street', models.CharField(max_length=512)),
                ('building_city', models.CharField(max_length=512)),
                ('building_state', models.CharField(max_length=512)),
                ('building_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.country')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.day')),
                ('food_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.foodbank')),
            ],
        ),
    ]
