# Generated by Django 3.2.5 on 2021-10-22 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0005_foodbank_workingdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
