# Generated by Django 3.2.5 on 2021-10-22 19:47

from django.db import migrations, models
import octopus.models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0006_foodbank_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='logo',
            field=models.ImageField(null=False, upload_to=octopus.models.file_name),
        ),
    ]
