# Generated by Django 3.2.5 on 2021-10-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0007_foodbank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodbank',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
