# Generated by Django 3.2.5 on 2021-10-23 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0008_alter_foodbank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, ),

        ),
        migrations.AddField(
            model_name='foodbank',
            name='edited_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
