# Generated by Django 3.2.5 on 2021-10-23 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0010_auto_20211023_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_adress',
            field=models.EmailField(default='bc.gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateField()),
                ('requested_packages', models.PositiveBigIntegerField()),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.user')),
                ('requested_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='octopus.foodbank')),
            ],
        ),
    ]
