# Generated by Django 3.2.5 on 2021-10-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0011_auto_20211023_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
