# Generated by Django 3.2.5 on 2021-10-23 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0013_remove_user_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestticket',
            name='note',
            field=models.TextField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestticket',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestticket',
            name='pickup_time',
            field=models.TimeField(),
        ),
    ]
