# Generated by Django 3.2.5 on 2021-10-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0015_alter_requestticket_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbank',
            name='representative',
            field=models.BooleanField(default=False),
        ),
    ]
