# Generated by Django 3.2.5 on 2021-10-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0019_foodbank_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbank',
            name='representative',
        ),
        migrations.AddField(
            model_name='user',
            name='representative',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
