# Generated by Django 3.2.5 on 2021-10-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0020_auto_20211024_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbank',
            name='building_country',
        ),
    ]
