# Generated by Django 3.2.5 on 2021-10-24 10:24

from django.db import migrations, models
import octopus.models


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0023_requestticket_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=octopus.models.file_name),
        ),
    ]
