# Generated by Django 3.2.5 on 2021-10-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octopus', '0025_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodbank',
            name='maps_embed',
        ),
    ]
